### ISSUE TITLE
How to partition a NN into N stages without using N GPUs

### ISSUE THREAD

**Issue by liulixinkerry** [nict-wisdom/rannc#3]
Dear Author,
Thanks for your wonderful work. We are curious about whether it is possible to partition a NN into `N` stages (or an even more complicated configuration) without `N` GPUs. Since we try to launch rannc's partitioner to partition a NN on a small GPU (one or two GPUs) machine and then manually deploy the partitioned result on a much larger GPU cluster with our own runtime, supporting this feature will bring us much more flexibility and help us analyze the partitioned results more systematically. Thanks a lot!

**Comment by nict-wisdom** [comment]
The latest version has features for the purpose. (Some are experimental and have not been tested enough)

`PARTITIONING_DRY_RUN_NP` allows you to set a number of GPUs regardless of the actual number.
You can set this by either of:

- Environment variable `RANNC_PARTITIONING_DRY_RUN_NP`
- `partitioning_dry_run_np` in the configuration file (should be located at `${HOME}/.pyrannc/rannc_conf.toml`)

(The [document](https://nict-wisdom.github.io/rannc/config.html) explains how to set RaNNC's configurations, but this item is not listed because it's still experimental)

To run our resnet example, first add the item to set the variable in `run_rannc.sh`.

```
# run_rannc.sh
# Set the number of GPUs in your environment.
MPI_OPTS+=" -x RANNC_PARTITIONING_DRY_RUN_NP=4"
```

Then you can run the training script with a single GPU while RaNNC assumes 4 GPUs are given.
You may need the partitioning result later, so set `SAVE_DEPLOYMENT=true` and `DEPLOYMENT_FILE=[PATH]` to save it.

```
NP=1 MODEL=resnet152x8 BATCH_SIZE= SAVE_DEPLOYMENT=true DEPLOYMENT_FILE=${HOME}/.rannc/cache/partitioning_resnet152x8.bin DATA_DIR=[DATA_PATH] sh ./run_rannc.sh
```

In this configuration, RaNNC assumes the effective batch size is 64 (16/process).
Please make sure that the partitioning was output at the specified location.

```
<RaNNCModule>: Saving deployment state to .../.rannc/cache/partitioning_resnet152x8.bin
```

Now you can use the partitioning with the expected number of GPUs (=4 in this example).
Set the batch size to 64 because this script takes the effective batch size across all GPUs.
RaNNC skips the search for partitioning and loads the precomputed partitioning when `LOAD_DEPLOYMENT=true` is given.

```
NP=4 MODEL=resnet152x8 BATCH_SIZE=64 SAVE_DEPLOYMENT=false LOAD_DEPLOYMENT=true DEPLOYMENT_FILE=${HOME}/.rannc/cache/partitioning_resnet152x8.bin DATA_DIR=[DATA_PATH] sh ./run_rannc.sh
```
(Please don't forget to disable `MPI_OPTS+=" -x RANNC_PARTITIONING_DRY_RUN_NP=4"`)

The following may help you inspect the partitioning.

```
python -c 'import pyrannc; pyrannc.show_deployment(".../.rannc/cache/partitioning_resnet152x8.bin", 64)'
```

The second argument is an expected batch size.
You can see the partitioning result as a collection of subgraphs and expected sizes of *micro batches* in pipeline parallelism.

**Comment by nict-wisdom** [comment]
The feature for *dry run* using a single GPU may encounter OOM even though RaNNC can successfully partition the model using more GPUs.

In such a case, I recommend you should try to increase *MIN_PIPELINE* (See [configurations](https://nict-wisdom.github.io/rannc/config.html).
This reduces the memory usage for profiling.

**Comment by liulixinkerry** [comment]
Thank you for your detailed and clear explanation! That works for me!
